USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS DOMAIN_ITEM_METADATA_FIELD
    (
        ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
        DOMAIN_ID NUMBER(38,0) CONSTRAINT FK_DOMAIN_ID FOREIGN KEY REFERENCES DOMAINS(ID),
        FIELD_NAME VARCHAR,
        AGGREGATION_METHOD VARCHAR
    );