USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS DOMAINS (
    ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
    NAME VARCHAR(100),
    RETENTION BOOLEAN DEFAULT FALSE
);

/*
INSERT INTO DOMAINS (NAME, RETENTION) 
VALUES('Patient', TRUE);
*/