USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS TABLE_LINKS (
    ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
    DOMAIN_ID NUMBER(38,0) CONSTRAINT FK_DOMAIN_ID FOREIGN KEY REFERENCES DOMAINS(ID),
    SOURCE_ID NUMBER(38,0),
    PK_TABLE_NAME VARCHAR(100),
    PK_COLUMN_NAME VARCHAR(100),
    FK_TABLE_NAME VARCHAR(100),
    FK_COLUMN_NAME VARCHAR(100),
    ALIAS VARCHAR(100),
    SORT_ORDER NUMBER(38,0),
    PK_VIEW_NAME VARCHAR(100),
    FK_VIEW_NAME VARCHAR(100)
);
ALTER TABLE TABLE_LINKS
ADD COLUMN IF NOT EXISTS 
            DOMAIN_ID NUMBER(38,0);-- CONSTRAINT FK_DOMAIN_ID FOREIGN KEY REFERENCES DOMAINS(ID)
ALTER TABLE TABLE_LINKS
ADD COLUMN IF NOT EXISTS PK_VIEW_NAME VARCHAR(100);
ALTER TABLE TABLE_LINKS
ADD COLUMN IF NOT EXISTS FK_VIEW_NAME VARCHAR(100);
ALTER TABLE TABLE_LINKS
ADD COLUMN IF NOT EXISTS ALIAS VARCHAR(100);
ALTER TABLE TABLE_LINKS
ADD COLUMN IF NOT EXISTS SORT_ORDER NUMBER(38,0);

ALTER TABLE TABLE_LINKS
DROP COLUMN IF EXISTS APP_NAME;

UPDATE TABLE_LINKS
SET DOMAIN_ID = 1
WHERE DOMAIN_ID IS NULL;

UPDATE TABLE_LINKS
SET PK_TABLE_NAME = REPLACE(PK_TABLE_NAME,'VIEW_',''),
    FK_TABLE_NAME = REPLACE(FK_TABLE_NAME,'VIEW_',''),
    PK_VIEW_NAME = 'VIEW_' || REPLACE(PK_TABLE_NAME,'VIEW_',''),
    FK_VIEW_NAME = 'VIEW_' || REPLACE(FK_TABLE_NAME,'VIEW_','')
;

/*
SET SOURCE_ID = (SELECT ID FROM SOURCES WHERE NAME = 'Insight_Plus_Patient');

INSERT INTO TABLE_LINKS (SOURCE_ID,PK_TABLE_NAME,PK_COLUMN_NAME,FK_TABLE_NAME,FK_COLUMN_NAME)
VALUES($SOURCE_ID,'ODS_CONTACT','ID','ODS_EPISODEOFCARE','Clients__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_ADVERSE_EVENT_COMPLAINT','Episode_of_Care__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_APPOINTMENT','Clinical_Case__c')
,($SOURCE_ID,'ODS_APPOINTMENT','ID','ODS_GROUP_APPOINTMENT','Appointment__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_RISK','Clinical_Case__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_SMS','Episode_of_Care__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_TASK','WhatId')
,($SOURCE_ID,'ODS_APPOINTMENT','ID','ODS_ADDITIONAL_QUESTIONNAIRE','Appointment__c')
,($SOURCE_ID,'ODS_APPOINTMENT','ID','ODS_CLIENT_QUESTIONNAIRE','Appointment__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_EMAILMESSAGE','RelatedToId')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_EMPLOYMENT_APPOINTMENT','Episode_of_Care__c')
,($SOURCE_ID,'ODS_APPOINTMENT','ID','ODS_QUESTIONNAIRE','Appointment__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_DIGITAL_REFERRAL','Episode_of_Care__c')
,($SOURCE_ID,'ODS_EPISODEOFCARE','ID','ODS_ATTACHMENT','ParentId')
;

SET SOURCE_ID = (SELECT ID FROM SOURCES WHERE NAME = 'Elemental_Patient');

INSERT INTO TABLE_LINKS (SOURCE_ID,PK_TABLE_NAME,PK_COLUMN_NAME,FK_TABLE_NAME,FK_COLUMN_NAME)
VALUES($SOURCE_ID,'ODS_HUB','ID','ODS_CLIENT','IDPRIMARYASSOCIATEDHUB')
,($SOURCE_ID,'ODS_CLIENT','ID','ODS_CASEINSTANCE','IDCLIENT')
,($SOURCE_ID,'ODS_CLIENT','ID','ODS_CLIENT_DATAVALUE','IDCLIENT')
,($SOURCE_ID,'ODS_CLIENT','ID','ODS_CLIENT_CLINIC_JOIN','IDCLIENT')
,($SOURCE_ID,'ODS_CLIENT_CLINIC_JOIN','IDCLINIC','ODS_CLINIC','ID')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_INTERVENTIONS_PRESCRIPTION','IDCASE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_INTERVENTIONS_PRESCRIPTION_MEETING','IDCASE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_INTERVENTIONS_SIGNPOSTING','IDCASE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_REFERRAL','IDCASEINSTANCE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_APPOINTMENT','IDCASE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_INTERVENTIONS_SIGNPOSTING','IDCASE')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_VISIT','IDCASE')
,($SOURCE_ID,'ODS_CASE_VISIT','ID','ODS_CASE_VISIT_OUTCOME_TYPE_JOIN','IDCASEVISIT')
,($SOURCE_ID,'ODS_CASEINSTANCE','ID','ODS_CASE_GOAL','IDCASE')
;

SET SOURCE_ID = (SELECT ID FROM SOURCES WHERE NAME = 'IAPTUS_Patient');

INSERT INTO TABLE_LINKS (SOURCE_ID,PK_TABLE_NAME,PK_COLUMN_NAME,FK_TABLE_NAME,FK_COLUMN_NAME)
VALUES($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_PATIENT_CONSENT','patient_id')
,($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_PATIENT_EXTRA_FIELDS','patient_id')
,($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_PATIENT_LABELS','pat_id')
,($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_TREATMENTS','patient_id')
,($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_DISABILITIES','PATIENT_ID')
,($SOURCE_ID,'ODS_PATIENTS','patient_id','ODS_LONG_TERM_CONDITIONS','PATIENT_ID')
,($SOURCE_ID,'ODS_TREATMENTS','TREATMENT_ID','ODS_SESSIONS','TREATMENT_ID')
,($SOURCE_ID,'ODS_SESSIONS','SESSION_ID','ODS_SESSIONS_EXTRA_FIELDS','SESSION_ID')
,($SOURCE_ID,'ODS_TREATMENTS','TREATMENT_ID','ODS_CAREPATHWAYS','TREATMENT_ID')
,($SOURCE_ID,'ODS_TREATMENTS','TREATMENT_ID','ODS_DIAGNOSES','TREATMENT_ID')
,($SOURCE_ID,'ODS_TREATMENTS','TREATMENT_ID','ODS_MEDICATIONS','TREATMENT_ID')
,($SOURCE_ID,'ODS_TREATMENTS','TREATMENT_ID','ODS_RESULTS','TREATMENT_ID')
,($SOURCE_ID,'ODS_RESULTS','RESULTS_ID','ODS_RESULT_ANSWERS','RESULTS_ID')
,($SOURCE_ID,'ODS_RESULTS','RESULTS_ID','ODS_RESULT_TOTALS','RESULTS_ID')
;

SET SOURCE_ID = (SELECT ID FROM SOURCES WHERE NAME = 'MHCP_Patient');

INSERT INTO TABLE_LINKS (SOURCE_ID,PK_TABLE_NAME,PK_COLUMN_NAME,FK_TABLE_NAME,FK_COLUMN_NAME)
VALUES($SOURCE_ID,'ODS_ Account','ID','ODS_CONTACT','AccountId')
,($SOURCE_ID,'ODS_CONTACT','ID','ODS_TREATMENT_EPISODE','Client__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_ASSESSMENT','Treatment_Episode__c')
,($SOURCE_ID,'ODS_ASSESSMENT','ID','ODS_ASSESSMENT_SIGNIFICANT_ENTRY','Assessment__c')
,($SOURCE_ID,'ODS_ASSESSMENT','ID','ODS_ASSESSMENT_SUPPORT_PLAN_LINK','Assessment__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_BED_OCCUPANCY','Treatment_Episode__c')
,($SOURCE_ID,'ODS_CONTACT','ID','ODS_KEY_CONTACTS','Clients__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_OUTCOMES','Care_Support_Episode__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_SUPPORT_PLAN','Treatment_Episode__c')
,($SOURCE_ID,'ODS_SUPPORT_PLAN','ID','ODS_EVALUATION','Support_Plan__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_RFA','CareSupportEpisode__c')
,($SOURCE_ID,'ODS_RFA','ID','ODS_RFASIGNIFICANTENTRY','RecoveryFocussedAssessment__c')
,($SOURCE_ID,'ODS_SUPPORT_PLAN','ID','ODS_RFASUPPORTPLAN','SupportPlan__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_SIGNIFICANT_ENTRY','Treatment_Episode__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_WAITING_LIST_OCCUPANCY','Treatment_Episode__c')
,($SOURCE_ID,'ODS_TREATMENT_EPISODE','ID','ODS_ATTACHMENT','ParentId')
;

SET SOURCE_ID = (SELECT ID FROM SOURCES WHERE NAME = 'NTEA_Patient');

INSERT INTO TABLE_LINKS (SOURCE_ID,PK_TABLE_NAME,PK_COLUMN_NAME,FK_TABLE_NAME,FK_COLUMN_NAME)
VALUES($SOURCE_ID,'ODS_CASE','ID','ODS_ADVERSE_EVENT_COMPLAINTS','CASE__C')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_APPOINTMENT','CONTACT_NAME__C')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_ASSESSMENT','CONTACT_NAME__C')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_CASE','CONTACTID')
    ,($SOURCE_ID,'ODS_ACCOUNT','ID','ODS_CONTACT','ACCOUNTID')
    ,($SOURCE_ID,'ODS_CASE','ID','ODS_EMAILMESSAGE','PARENTID')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_EVENT','WHOID')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_QUESTIONNAIRE','CONTACT__C')
    ,($SOURCE_ID,'ODS_CONTACT','ID','ODS_TASK','WHOID')
    ,($SOURCE_ID,'ODS_CASE','ID','ODS_ATTACHMENT','ParentId')
;

*/