USE DATABASE SSOT;
USE SCHEMA NHS;
CREATE OR REPLACE VIEW VIEW_ASSESSMENT_TYPE
AS
SELECT  * EXCLUDE EXTRACT_TS
FROM ASSESSMENT_TYPE
QUALIFY ROW_NUMBER() OVER (PARTITION BY ID ORDER BY EXTRACT_TS DESC) = 1;