USE DATABASE SSOT;
USE SCHEMA NHS;
CREATE TABLE IF NOT EXISTS APPOINTMENT
    (
        ID NUMBER(38,0) UNIQUE,
        PATIENT_ID NUMBER(38,0) FOREIGN KEY REFERENCES PATIENT(ID),
        CLINICIAN_NAME VARCHAR(1000),
        NOTES VARCHAR,
        SCHEDULED_DATE DATE,
        ACTUAL_DATE DATE,
        CANCELLED BOOLEAN,
        LAST_MODIFIED TIMESTAMP_NTZ(0),
        EXTRACT_TS TIMESTAMP_NTZ(0)
    );

/*################## EXAMPLE INSERTS ################## 
USE DATABASE SSOT;
USE SCHEMA NHS;

*/