USE DATABASE SSOT;
USE SCHEMA NHS;
CREATE TABLE IF NOT EXISTS ASSESSMENT_TYPE
    (
        ID NUMBER(38,0) UNIQUE,
        ASSESSMENT_TYPE VARCHAR(100),
        ASSESSMENT_DESCRIPTION VARCHAR(1000),
        ENABLED BOOLEAN,
        LAST_MODIFIED TIMESTAMP_NTZ(0),
        EXTRACT_TS TIMESTAMP_NTZ(0)
    );

/*################## EXAMPLE INSERTS ################## 
USE DATABASE SSOT;
USE SCHEMA NHS;

*/