USE DATABASE SSOT;
USE SCHEMA NHS;
CREATE TABLE IF NOT EXISTS APPOINTMENT
    (
        ID NUMBER(38,0) UNIQUE,
        APPOINTMENT_ID NUMBER(38,0) FOREIGN KEY REFERENCES APPOINTMENT(ID),
        ASSESSMENT_TYPE_ID NUMBER(38,0) FOREIGN KEY REFERENCES ASSESSMENT_TYPE(ID),
        SCHEDULED_DATE DATE,
        ACTUAL_DATE DATE,
        CANCELLED BOOLEAN,
        LAST_MODIFIED TIMESTAMP_NTZ(0),
        EXTRACT_TS TIMESTAMP_NTZ(0)
    );

/*################## EXAMPLE INSERTS ################## 
USE DATABASE SSOT;
USE SCHEMA NHS;

*/