USE DATABASE SSOT;
USE SCHEMA NHS;
CREATE TABLE IF NOT EXISTS PATIENT
    (
        ID NUMBER(38,0) UNIQUE,
        NHS_NUMBER NUMBER(38,0),
        FIRST_NAME VARCHAR(255),
        LAST_NAME VARCHAR(255),
        DATE_OF_BIRTH DATE,
        DATE_OF_DEATH DATE,
        POST_CODE VARCHAR(10),
        EMAIL_ADDRESS VARCHAR(500),
        LAST_MODIFIED TIMESTAMP_NTZ(0),
        EXTRACT_TS TIMESTAMP_NTZ(0)
    );

/*################## EXAMPLE INSERTS ################## 
USE DATABASE SSOT;
USE SCHEMA NHS;

*/