USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA PATIENT;
CREATE OR REPLACE TASK TASK_CREATE_PATIENT_LINKS 
SCHEDULE = 'USING CRON 0 8 * * *  Europe/London'
WAREHOUSE = WH_CLEKT_{{ environment }} 
AS
--Create the patient links
CALL DOMAIN_CONFIG.CREATE_LINKS(1);

CREATE OR REPLACE TASK TASK_CREATE_PATIENT
WAREHOUSE = WH_CLEKT_{{ environment }} 
AFTER TASK_CREATE_PATIENT_LINKS
AS
--Create the patients in patient_master
CALL DOMAIN_CONFIG.CREATE_DOMAIN_ITEMS(1);

CREATE OR REPLACE TASK TASK_GENERATE_PATIENT_METADATA
WAREHOUSE = WH_CLEKT_{{ environment }} 
AFTER TASK_CREATE_PATIENT
AS
--Execute the DT and View build using the metadata definitions
DECLARE source_id NUMBER(38,0) DEFAULT 1;
        domain_id NUMBER(38,0) DEFAULT 1;
    source_cursor CURSOR FOR 
SELECT DISTINCT SOURCE_ID
FROM PATIENT.SOURCES
    JOIN DOMAIN_CONFIG.DOMAIN_ITEM_METADATA_CONFIG CONF ON CONF.SOURCE_ID = SOURCES.ID
    JOIN DOMAIN_CONFIG.DOMAIN_ITEM_METADATA_FIELD FIELD ON FIELD.ID = CONF.METADATA_FIELD_ID
WHERE DOMAIN_ID = ?
;
BEGIN
OPEN source_cursor USING (domain_id);
--Generate the DTs used for the View
FOR sources IN source_cursor DO
    source_id := sources.source_id;
    CALL DOMAIN_CONFIG.GENERATE_DOMAIN_ITEM_METADATA_DT(:domain_id,:source_id,0,1);
END FOR;
CLOSE source_cursor;
--Generate the view using the DTs
CALL DOMAIN_CONFIG.GENERATE_DOMAIN_ITEM_METADATA_VW(:domain_id);
END;

CREATE OR REPLACE TASK TASK_UPDATE_PATIENT_METADATA
WAREHOUSE = WH_CLEKT_{{ environment }} 
AFTER TASK_GENERATE_PATIENT_METADATA
AS
--Perform the Metadata Update on Patient
CALL DOMAIN_CONFIG.UPDATE_DOMAIN_ITEM_METADATA(1);
;

EXECUTE IMMEDIATE $$ 
BEGIN 
    IF ('{{environment}}' = 'PROD') THEN 
        SELECT SYSTEM$TASK_DEPENDENTS_ENABLE('TASK_CREATE_PATIENT_LINKS');
    END IF;
END
$$;