USE DATABASE FOUNDATION;
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS DOMAIN_ITEM_METADATA_CONFIG
    (
        ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
        METADATA_FIELD_ID NUMBER(38,0) CONSTRAINT FK_FIELD_ID FOREIGN KEY REFERENCES DOMAIN_ITEM_METADATA_FIELD(ID),
        SOURCE_ID NUMBER(38,0),
        CALCULATION VARCHAR
    );