USE DATABASE FOUNDATION;
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS DOMAINS (
    ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
    NAME VARCHAR(100)
);

/*################## EXAMPLE INSERTS ################## 
USE DATABASE FOUNDATION;
USE SCHEMA DOMAIN_CONFIG;

INSERT INTO DOMAINS (NAME)
VALUES('PATIENT');

*/