USE DATABASE FOUNDATION;
USE SCHEMA DOMAIN_CONFIG;
CREATE TABLE IF NOT EXISTS TABLE_LINKS (
    ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
    DOMAIN_ID NUMBER(38,0) CONSTRAINT FK_DOMAIN_ID FOREIGN KEY REFERENCES DOMAINS(ID),
    SOURCE_ID NUMBER(38,0),
    PK_TABLE_NAME VARCHAR(100),
    PK_COLUMN_NAME VARCHAR(100),
    FK_TABLE_NAME VARCHAR(100),
    FK_COLUMN_NAME VARCHAR(100),
    ALIAS VARCHAR(100),
    SORT_ORDER NUMBER(38,0),
    PK_VIEW_NAME VARCHAR(100),
    FK_VIEW_NAME VARCHAR(100)
);