USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA PATIENT;
CREATE TABLE IF NOT EXISTS PATIENT_LINKS (
    ID NUMBER(38,0) AUTOINCREMENT(1,1) PRIMARY KEY UNIQUE,
    PATIENT_ID NUMBER(38,0)  CONSTRAINT FK_PATIENT_ID FOREIGN KEY REFERENCES PATIENT_MASTER(ID),
    SOURCE_ID NUMBER(38,0) CONSTRAINT FK_SOURCE_ID FOREIGN KEY REFERENCES SOURCES(ID),
    UID VARCHAR(1000),    -- Field that links to multiple patient tables within the source systems based on the other fields.
    LAST_MODIFIED_TS TIMESTAMP_NTZ,
    LAST_MODIFIED_BY VARCHAR(100)
);