USE DATABASE FOUNDATION_{{dbname}};
USE SCHEMA PATIENT;
ALTER TABLE IF EXISTS DOMAIN_CONFIG.SOURCES RENAME COLUMN LAST_MODIFIED_FIELD TO LAST_MODIFIED_TS_FIELD;
ALTER TABLE IF EXISTS DOMAIN_CONFIG.SOURCES DROP COLUMN DOMAIN_ID;
ALTER TABLE IF EXISTS DOMAIN_CONFIG.SOURCES ADD COLUMN ROOT_VIEW_NAME VARCHAR(100);
ALTER TABLE IF EXISTS DOMAIN_CONFIG.SOURCES RENAME TO PATIENT.SOURCES;
CREATE TABLE IF NOT EXISTS SOURCES (
    ID NUMBER(38,0) AUTOINCREMENT PRIMARY KEY UNIQUE,
    NAME VARCHAR(100),
    ENABLED BOOLEAN,
    PRIORITY NUMBER(10,0),
    ROOT_TABLE_SCHEMA VARCHAR(100),
    ROOT_TABLE_NAME VARCHAR(100),
    ROOT_VIEW_NAME VARCHAR(100),
    ROOT_TABLE_FILTER VARCHAR(1000),
    UNMATCHABLE_LOGIC VARCHAR,  -- This is a WHERE clause that finds any records that don't meet the minimum criteria
                                -- E.g. Patients require at least 
                                -- NHS Number OR First Name, Last Name, DOB, Post Code OR Email and DOB
                                --Exmaple to find records that :
                                -- NHS_NUMBER IS NULL AND 
                                -- (FIRST_NAME IS NULL OR LAST_NAME IS NULL OR DOB IS NULL OR POST_CODE IS NULL)
                                -- AND (EMAIL_ADDRESS IS NULL OR DOB IS NULL)
    UID_FIELD VARCHAR(100),
    LAST_MODIFIED_TS_FIELD VARCHAR(100),
    NHS_NUMBER_FIELD VARCHAR(100),
    FIRST_NAME_FIELD VARCHAR(100),
    LAST_NAME_FIELD VARCHAR(100),
    DOB_FIELD VARCHAR(100),
    POST_CODE_FIELD VARCHAR(100),
    EMAIL_ADDRESS_FIELD VARCHAR(100)
);

-- Update field values to be fully qualified e.g. ROOT.ID rather than just ID
UPDATE SOURCES
SET   UID_FIELD               = 'ROOT.' || UID_FIELD,
      LAST_MODIFIED_TS_FIELD  = 'ROOT.' || LAST_MODIFIED_TS_FIELD,
      NHS_NUMBER_FIELD        = 'TRY_TO_DECIMAL(ROOT.' || NHS_NUMBER_FIELD || ')',
      FIRST_NAME_FIELD        = 'ROOT.' || FIRST_NAME_FIELD,
      LAST_NAME_FIELD         = 'ROOT.' || LAST_NAME_FIELD,
      DOB_FIELD               = 'ROOT.' || DOB_FIELD,
      POST_CODE_FIELD         = 'ROOT.' || POST_CODE_FIELD,
      EMAIL_ADDRESS_FIELD     = 'ROOT.' || EMAIL_ADDRESS_FIELD,
      ROOT_TABLE_NAME         = REPLACE(ROOT_TABLE_NAME,'VIEW_',''),
      ROOT_VIEW_NAME          = 'VIEW_' || REPLACE(ROOT_TABLE_NAME,'VIEW_','')
WHERE SOURCES.UID_FIELD NOT LIKE 'ROOT.%'
;

/*
SET patient_id = (SELECT ID FROM DOMAINS WHERE NAME = 'Patient');

INSERT INTO SOURCES (DOMAIN_ID,NAME,ENABLED,PRIORITY,ROOT_TABLE_SCHEMA,ROOT_TABLE_NAME,ROOT_TABLE_FILTER,UID_FIELD,UNMATCHABLE_LOGIC) 
VALUES($patient_id,'Insight_Plus_Patient',TRUE,1,'IAPT','ODS_CONTACT','AND RECORDTYPEID = \'012b0000000QEc0AAG\'','ID','NHS_NUMBER IS NULL
AND
(FIRST_NAME IS NULL
OR LAST_NAME IS NULL
OR DOB IS NULL
OR POST_CODE IS NULL)
AND 
(EMAIL_ADDRESS IS NULL
OR DOB IS NULL)'),
      ($patient_id,'Elemental_Patient',TRUE,2,'ELEMENTAL','ODS_CLIENT',NULL,'ID','NHS_NUMBER IS NULL
AND
(FIRST_NAME IS NULL
OR LAST_NAME IS NULL
OR DOB IS NULL
OR POST_CODE IS NULL)
AND 
(EMAIL_ADDRESS IS NULL
OR DOB IS NULL)'),
      ($patient_id,'IAPTUS_Patient',TRUE,3,'IAPTUS','ODS_PATIENTS',NULL,'PATIENT_ID','NHS_NUMBER IS NULL
AND
(FIRST_NAME IS NULL
OR LAST_NAME IS NULL
OR DOB IS NULL
OR POST_CODE IS NULL)
AND 
(EMAIL_ADDRESS IS NULL
OR DOB IS NULL)'),
      ($patient_id,'MHCP_Patient',TRUE,4,'MHCP','ODS_CONTACTS','AND RECORDTYPEID IN(\'0124H000000cxmrQAA\',\'0124H000000cxmsQAA\')','ID','NHS_NUMBER IS NULL
AND
(FIRST_NAME IS NULL
OR LAST_NAME IS NULL
OR DOB IS NULL
OR POST_CODE IS NULL)
AND 
(EMAIL_ADDRESS IS NULL
OR DOB IS NULL)'),
      ($patient_id,'NTEA_Patient',TRUE,5,'NTEA','ODS_CONTACT',NULL,'ID','NHS_NUMBER IS NULL
AND
(FIRST_NAME IS NULL
OR LAST_NAME IS NULL
OR DOB IS NULL
OR POST_CODE IS NULL)
AND 
(EMAIL_ADDRESS IS NULL
OR DOB IS NULL)')
;

-- IAPT
UPDATE SOURCES
SET   NHS_NUMBER_FIELD = 'NHS_NUMBER__C',
      FIRST_NAME_FIELD = 'FIRSTNAME',
      LAST_NAME_FIELD = 'LASTNAME',
      DOB_FIELD = 'DATE_OF_BIRTH__C',
      POST_CODE_FIELD = 'POSTCODE__C',
      EMAIL_ADDRESS_FIELD = 'EMAIL',
      LAST_MODIFIED_FIELD = 'LASTMODIFIEDDATE'
WHERE ID = 1;

-- ELEMENTAL
UPDATE SOURCES
SET   NHS_NUMBER_FIELD = 'MEDICALNUMBER',
      FIRST_NAME_FIELD = 'FIRSTNAME',
      LAST_NAME_FIELD = 'SURNAME',
      DOB_FIELD = 'DOB',
      POST_CODE_FIELD = 'POSTCODE',
      EMAIL_ADDRESS_FIELD = 'EMAIL',
      LAST_MODIFIED_FIELD = 'EXTRACT_TS'
WHERE ID = 2;

-- IAPTUS
UPDATE SOURCES
SET   NHS_NUMBER_FIELD = 'NHS_NUMBER',
      FIRST_NAME_FIELD = 'FIRST_NAME',
      LAST_NAME_FIELD = 'LAST_NAME',
      DOB_FIELD = 'DOB',
      POST_CODE_FIELD = 'POSTCODE',
      EMAIL_ADDRESS_FIELD = 'EMAIL',
      LAST_MODIFIED_FIELD = 'EXTRACT_TS'
WHERE ID = 3;

-- MHCP
UPDATE SOURCES
SET   NHS_NUMBER_FIELD = 'NHS_NUMBER__C',
      FIRST_NAME_FIELD = 'FIRST_NAMES__C',
      LAST_NAME_FIELD = 'SURNAME__C',
      DOB_FIELD = 'DATE_OF_BIRTH__C',
      POST_CODE_FIELD = 'POST_CODE__C',
      EMAIL_ADDRESS_FIELD = 'EMAIL__C',
      LAST_MODIFIED_FIELD = 'LASTMODIFIEDDATE'
WHERE ID = 4;

-- NTEA
UPDATE SOURCES
SET   NHS_NUMBER_FIELD = 'CONTACTSOURCE',
      FIRST_NAME_FIELD = 'FIRSTNAME',
      LAST_NAME_FIELD = 'LASTNAME',
      DOB_FIELD = 'BIRTHDATE',
      POST_CODE_FIELD = 'MAILINGPOSTALCODE',
      EMAIL_ADDRESS_FIELD = 'EMAIL',
      LAST_MODIFIED_FIELD = 'LASTMODIFIEDDATE'
WHERE ID = 5
*/